# Full Example: https://github.com/geekan/MetaGPT/blob/main/config/config2.example.yaml
# Reflected Code: https://github.com/geekan/MetaGPT/blob/main/metagpt/config2.py
# Config Docs: https://docs.deepwisdom.ai/main/en/guide/get_started/configuration.html
# llm:
#   api_type: "zhipuai" # or azure / ollama / groq etc.
#   model: "glm-4-alltools" # or gpt-3.5-turbo
#   # base_url: "https://api.deepseek.com" # or forward url / other llm url
#   api_key: "20dfce770d07c086ec566ed264bfa8df.q9kjMZzhJhLU96W1"

llm:
  api_type: "dashscope"
  base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
  model: "qwen-max"
  api_key: "sk-3eb46edc645e4a789c5754a472bc5760"

embedding:
  api_type: "ollama"
  base_url: "http://192.168.35.235:11434"
  model: "qwen2:1.5b"
  dimensions: 1536

# proxy: "http://127.0.0.1:7890"
